spring:
  datasource:
    mariadb:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
      username: root
      password: 1234
  messagesource:
    basename: classpath:querySource
    default-encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:views/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false